### ISSUE TITLE
mockoltpserver fails to receive metrics over gRPC

### ISSUE THREAD

**Issue by trentm** [elastic/elastic-otel-node#276]
Attempting to send metrics over OTLP/gRPC to mockotlpserver results in this error on the client side:

```
{"name":"elastic-otel-node","level":50,"msg":"{\"stack\":\"Error: PeriodicExportingMetricReader: metrics export failed (error Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.metrics.v1.MetricsService/Export)\\n    at doExport (/Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76:23)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async PeriodicExportingMetricReader._doRun (/Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:84:13)\\n    at async PeriodicExportingMetricReader._runOnce (/Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:55:13)\",\"message\":\"PeriodicExportingMetricReader: metrics export failed (error Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.metrics.v1.MetricsService/Export)\",\"name\":\"Error\"}","time":"2024-07-10T21:58:25.149Z"}
```

or the same error when using the vanilla OTel SDK on the client:

```
{"stack":"Error: PeriodicExportingMetricReader: metrics export failed (error Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.metrics.v1.MetricsService/Export)\n    at doExport (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PeriodicExportingMetricReader._doRun (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:84:13)\n    at async PeriodicExportingMetricReader._runOnce (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:55:13)","message":"PeriodicExportingMetricReader: metrics export failed (error Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.metrics.v1.MetricsService/Export)","name":"Error"}
```

Pretty printing a bit:

```
  "message": "PeriodicExportingMetricReader: metrics export failed (error Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.metrics.v1.MetricsService/Export)",
  "stack": "Error: PeriodicExportingMetricReader: metrics export failed (error Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.metrics.v1.MetricsService/Export)
    at doExport (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:76:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PeriodicExportingMetricReader._doRun (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:84:13)
    at async PeriodicExportingMetricReader._runOnce (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/sdk-metrics/build/src/export/PeriodicExportingMetricReader.js:55:13)"
```

# repro

1. start mockotlpserver

```
npm ci
cd packages/mockotlpserver
npm start
```

2. run this example:

```
cd examples
OTEL_METRIC_EXPORT_TIMEOUT=5000 \
  OTEL_METRIC_EXPORT_INTERVAL=10000 \
  OTEL_EXPORTER_OTLP_PROTOCOL=grpc node -r @elastic/opentelemetry-node http-server.js
```

After about 10s it will attempt a metrics export.

## updating protos doesn't help

Updating the protos to the latest doesn't help:

```diff
diff --git a/scripts/update-protos.js b/scripts/update-protos.js
old mode 100644
new mode 100755
index d8d6019..e726506
--- a/scripts/update-protos.js
+++ b/scripts/update-protos.js
@@ -47,7 +47,7 @@ const {tmpdir} = require('os');
 // SCRIPT PARAMS
 const REPO_NAME = 'opentelemetry-proto';
 const REPO_URL = `https://github.com/open-telemetry/${REPO_NAME}.git`;
-const HASH_TAG = 'v0.20.0';
+const HASH_TAG = 'v1.3.2';

 // HELPER FUNCTIONS
 /**
```

and running "./scripts/update-protos.js".

@david-luna Any ideas?

**Comment by trentm** [comment]
Ah, I suspect it is because it just isn't implemented yet in mockotlpserver:
https://github.com/elastic/elastic-otel-node/blob/84e7ea184092c8e6cad624c0a90049289d5a8879/packages/mockotlpserver/lib/grpc.js#L78-L84

**Comment by trentm** [comment]
Same issue with logs. Repro:

```
$ cd examples/
$ OTEL_EXPORTER_OTLP_PROTOCOL=grpc OTEL_NODE_RESOURCE_DETECTORS=none node -r @elastic/opentelemetry-node bunyan-logging-app.js
...
{"name":"elastic-otel-node","level":50,"msg":"{\"stack\":\"Error: 12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.logs.v1.LogsService/Export\\n    at callErrorFromStatus (/Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\\n    at Object.onReceiveStatus (/Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/client.js:193:76)\\n    at Object.onReceiveStatus (/Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\\n    at Object.onReceiveStatus (/Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\\n    at /Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78\\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\\nfor call at\\n    at ServiceClientImpl.makeUnaryRequest (/Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/client.js:161:32)\\n    at ServiceClientImpl.<anonymous> (/Users/trentm/el/elastic-otel-node4/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\\n    at /Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/instrumentation-grpc/build/src/clientUtils.js:131:31\\n    at /Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/instrumentation-grpc/build/src/instrumentation.js:211:209\\n    at AsyncLocalStorage.run (node:async_hooks:338:14)\\n    at AsyncLocalStorageContextManager.with (/Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)\\n    at ContextAPI.with (/Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)\\n    at ServiceClientImpl.clientMethodTrace [as export] (/Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/instrumentation-grpc/build/src/instrumentation.js:211:42)\\n    at /Users/trentm/el/elastic-otel-node4/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/grpc-exporter-transport.js:100:32\\n    at new Promise (<anonymous>)\",\"message\":\"12 UNIMPLEMENTED: The server does not implement the method /opentelemetry.proto.collector.logs.v1.LogsService/Export\",\"code\":\"12\",\"details\":\"The server does not implement the method /opentelemetry.proto.collector.logs.v1.LogsService/Export\",\"metadata\":\"[object Object]\",\"name\":\"Error\"}","time":"2024-07-10T22:19:12.354Z"}
```
