### ISSUE TITLE
flaky test: "system.cpu.utilization" data points have a value between 0-1

### ISSUE THREAD

**Issue by trentm** [elastic/elastic-otel-node#73]
Since, I think, #52 this test has been flaky. I've seen failures on two PRs now.

https://github.com/elastic/elastic-otel-node/actions/runs/7879432439/job/21499670394?pr=72

```
# host metrics
# host metrics default views
{"name":"mockotlpserver","level":30,"msg":"OTLP/HTTP listening at http://127.0.0.1:45709/","time":"2024-02-12T23:42:52.907Z"}
ok 7 exited successfully: err=null
ok 8 system.network.* metrics are dropped
ok 9 system.cpu.time metric is dropped
ok 10 data points are present in system.cpu.utilization metric
not ok 11 "system.cpu.utilization" data points have a value between 0-1
  ---
    operator: ok
    expected: true
    actual:   false
    at: <anonymous> (/home/runner/work/elastic-otel-node/elastic-otel-node/packages/opentelemetry-node/test/host-metrics.test.js:47:19)
    stack: |-
      Error: "system.cpu.utilization" data points have a value between 0-1
          at Test.assert [as _assert] (/home/runner/work/elastic-otel-node/elastic-otel-node/node_modules/tape/lib/test.js:479:48)
          at Test.assert (/home/runner/work/elastic-otel-node/elastic-otel-node/node_modules/tape/lib/test.js:612:7)
          at /home/runner/work/elastic-otel-node/elastic-otel-node/packages/opentelemetry-node/test/host-metrics.test.js:47:19
          at Array.forEach (<anonymous>)
          at Object.checkTelemetry (/home/runner/work/elastic-otel-node/elastic-otel-node/packages/opentelemetry-node/test/host-metrics.test.js:42:35)
          at done (/home/runner/work/elastic-otel-node/elastic-otel-node/packages/opentelemetry-node/test/testutils.js:504:42)
          at ChildProcess.exithandler (node:child_process:414:7)
          at ChildProcess.emit (node:events:519:28)
          at maybeClose (node:internal/child_process:1105:16)
          at ChildProcess._handle.onexit (node:internal/child_process:305:5)
  ...
ok 12 data points have no "system.cpu.state" attribute
```

**Comment by trentm** [comment]
^^  This is not relevant anymore, until/unless we bring `system.*` metrics back.
